---
- hosts: localhost
  
  tasks:

  - name: do a pingo to the localhost
    ping:
      data: hello

  - name: copy examplefile.txt to remote as hello.txt
    copy:
      src: examplefile.txt
      dest: /tmp/hello.txt
