---
# This playbook pings the host and copies a file to the remote location.
- hosts: localhost
  tasks:

  - name: do a pingo to the localhost
    ping:
      data: hello

  - name: copy examplefile.txt to remote as hello.txt in /tmp folder
    copy:
      src: examplefile.txt
      dest: /tmp/hello.txt
