---
- hosts: all
  gather_facts: yes
  remote_user: root

  pre_tasks:
  - name: Include app-related variables
    include_vars: vars/myapp.yml

  tasks:
  - name: Install/update Apache webserver
    apt:
      name: apache2
      state: latest
      update_cache: yes
  
  - name: Stop Apache if running
    service:
      name: apache2
      state: stopped
      enabled: yes

  - name: Copy website files to webserver
    copy:
      src: 'files/website/'
      dest: '{{ base_path }}/{{ app_dir }}' # Translates into /var/www/myapp

  - name: Copy and fill in VirtualHost template
    template:
      src: 'files/conf/virtualhost.conf'
      dest: '/etc/apache2/sites-available/{{ app_dir }}.conf'

  - name: Activate the new Virtual Host in Apache
    shell: 'a2ensite {{ app_dir }}.conf' # Run a freeform command
    args:
      chdir: /etc/apache2/sites-available/ # Change into this dir beforehand

  - name: Restart Apache
    service:
      name: apache2
      state: started
      enabled: yes

  # - name: Test whether the webpage can be accessed
